spring.application.name=PokeApiEquipo
<<<<<<< HEAD
=======
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ale.tena.r@gmail.com
spring.mail.password=ocqk rjbf awhr xtqw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
>>>>>>> origin/JMS-Correo
